#!/bin/bash
####################################################################
# Prey Network Module Lang File - by Juan C. Mardones (http://juanmardones.com)
# URL: http://preyproject.com
# License: GPLv3
####################################################################

STRING_GET_IP=" -- Obteniendo la direccion IP publica..."
STRING_GET_LAN_IP=" -- Obteniendo la direccion IP privada de la LAN..."
STRING_GET_MAC_AND_WIFI=" -- Obteniendo direccion MAC, tabla de rutas e informacion de la Red Wifi..."
STRING_TRACE=" -- Rastreando la ruta completa hacia Internet..."
