#!/bin/bash
####################################################################
# PREY Report Module Base Functions - by Tomas Pollak (bootlog.org)
# URL : http://preyproject.com
# License: GPLv3
####################################################################

function get_public_ip {
	public_ip=`$getter checkip.dyndns.org|sed -e 's/.*Current IP Address: //' -e 's/<.*$//'`
}

function get_internal_ip {
	# internal_ip=`ifconfig | grep "inet " | grep -v "127.0.0.1" | cut -f2 | awk '{ print $2}' | sed 's/addr://'`
	internal_ip=`ifconfig | grep inet | awk '{ print $2}' | sed 's/addr://'`
}

function trace_route {
	complete_trace=`$traceroute -q1 www.google.com 2>&1`
}

function get_uptime_and_processes {
	uptime=`uptime`
	running_programs=`ps ux`
}

function get_modified_files {
	# no incluimos los archivos carpetas ocultas ni los archivos weones de Mac OS
	modified_files=`find $modified_files_path \( ! -regex '.*/\..*/..*' \) -type f -mmin -$modified_files_time 2>&1`
	# archivos=`find ~/. \( ! -regex '.*/\..*/\.DS_Store' \) -type f -mmin -$minutos`
}

function get_active_connections {
	connections=`netstat -a | grep -i established`
}

function compress_screenshot {
	echo " -- Compressing screenshot..."
	tar zcf $screenshot.tar.gz $screenshot
	screenshot=$screenshot.tar.gz
}
