#!/bin/bash
####################################################################
# PREY Report Module Base Functions - by Tomas Pollak (bootlog.org)
# URL : http://prey.bootlog.org
# License: GPLv3
####################################################################

function get_public_ip {
	publico=`$getter checkip.dyndns.org|sed -e 's/.*Current IP Address: //' -e 's/<.*$//'`
}

function get_internal_ip {
	# works in mac as well as linux (linux just prints an extra "addr:")
	interno=`ifconfig | grep "inet " | grep -v "127.0.0.1" | cut -f2 | awk '{ print $2}'`
}

function trace_route {
	complete_trace=`$traceroute -q1 www.google.com 2>&1`
}

function get_uptime_and_processes {
	uptime=`uptime`
	programas=`ps ux`
}

function get_modified_files {
	# no incluimos los archivos carpetas ocultas ni los archivos weones de Mac OS
	archivos=`find $modified_files_path \( ! -regex '.*/\..*/..*' \) -type f -mmin -$modified_files_time 2>&1`
	# archivos=`find ~/. \( ! -regex '.*/\..*/\.DS_Store' \) -type f -mmin -$minutos`
}

function get_active_connections {
	connections=`netstat -a | grep -i established`
}

function compress_screenshot {
	echo " -- Compressing screenshot..."
	tar zcf $screenshot.tar.gz $screenshot
	screenshot=$screenshot.tar.gz
}

function write_email {
	. lang/$lang
}

function send_email {
	complete_subject="$subject @ `date +"%a, %e %Y %T %z"`"
	echo "$emailtext" > msg.tmp
	emailstatus=`./sendEmail -f "$from" -t "$emailtarget" -u "$complete_subject" -s $smtp_server -a $picture $screenshot -o message-file=msg.tmp tls=auto username=$smtp_username password=$smtp_password`

	if [[ "$emailstatus" =~ "ERROR" ]]; then
		echo -e "$STRING_ERROR_EMAIL"
	fi
}

function remove_evidence {
	if [ -e "$picture" ]; then
		rm $picture
	fi
	if [ -e "$screenshot" ]; then
		rm $screenshot
	fi
	rm msg.tmp
}
