#!/bin/bash
####################################################################
# PREY Report Module Mac Functions - by Tomas Pollak (bootlog.org)
# URL : http://preyproject.com
# License: GPLv3
####################################################################

function get_mac_address {
	# this one is actually the gateway's mac address!
	# mac_address=`arp -n $gateway_ip | cut -f4 -d' '`
	mac_address=`ifconfig | grep ether | sed -e 's/ether //g' -e 's/^[^a-z0-9]//g' | head -1`
}

function get_images {
	screencapture='/usr/sbin/screencapture -mx'

	if [ `whoami` == 'root' ]; then # we need to get the PID of the loginwindow and take the screenshot through launchctl

		loginpid=`ps -ax | grep loginwindow.app | grep -v grep | awk '{print $1}'`
		launchctl bsexec $loginpid $screencapture $screenshot

	else

		$screencapture $screenshot

	fi

	# ok, lets see if the computer is able to take a picture with its iSight
	$module_path/lib/isightcapture $picture
}
