#!/bin/bash
####################################################################
# PREY Report Module Mac Functions - by Tomas Pollak (bootlog.org)
# URL : http://preyproject.com
# License: GPLv3
####################################################################

function get_mac_address {
	mac_address=`arp -n $gateway_ip | cut -f4 -d' '`
}

function get_images {
	screencapture='/usr/sbin/screencapture -mx'

	if [ `whoami` == 'root' ]; then # we need to get the PID of the loginwindow and take the screenshot through launchctl

		loginpid=`ps -ax | grep loginwindow.app | grep -v grep | awk '{print $1}'`
		launchctl bsexec $loginpid $screencapture $screenshot

	else

		$screencapture $screenshot

	fi

	# muy bien, veamos si el tarro puede sacar una imagen con la webcam
	$module_path/lib/isightcapture $picture
}
