#!/bin/bash
####################################################################
# PREY Report Module Mac Functions - by Tomas Pollak (bootlog.org)
# URL : http://prey.bootlog.org
# License: GPLv3
####################################################################

function get_network_info {
	airport='/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport'
	routes=`netstat -rn | grep default | cut -c20-35`
	mac=`arp -n $routes | cut -f4 -d' '`
	if [ ! -n "$wifi_info" ]; then
		wifi_info=`$airport -I | grep -v "Off"`
	fi
}

function get_images {
	screencapture='/usr/sbin/screencapture -mx'

	if [ `whoami` == 'root' ]; then # we need to get the PID of the loginwindow and take the screenshot through launchctl

		loginpid=`ps -ax | grep loginwindow.app | grep -v grep | awk '{print $1}'`
		launchctl bsexec $loginpid $screencapture $screenshot

	else

		$screencapture $screnshot

	fi

	# muy bien, veamos si el tarro puede sacar una imagen con la webcam
	$module_path/lib/isightcapture $picture
}
