#!/bin/bash
####################################################################
# PREY Report Module Windows Functions - by Tomas Pollak (bootlog.org)
# URL : http://preyproject.com
# License: GPLv3
####################################################################

function get_mac_address {
	mac_address=`ipconfig | grep Physical | sed 's/^.*: //g' | head -1`
}

function get_images {
	echo ' !! TODO yet!'
}
