#!/bin/bash
####################################################################
# PREY Configuration File - by Tomas Pollak (bootlog.org)
# URL : http://prey.bootlog.org
# License: GPLv3
####################################################################

# language, english or spanish
lang='english'

# verification URL, if left empty Prey will always gather and send the information
url=''

# mailbox to send the report
emailtarget='mailbox@domain.com'

# SMTP configuration
# TODO: store the password in an encrypted formt
# don't worry, this file will be unaccesible for other users anyway
smtp_server='smtp.gmail.com:587'
smtp_username='username@gmail.com'
smtp_password='password'

####################################################################
# optional configuration, some of this is still experimental
####################################################################

# email settings
from='Prey <no-reply@gmail.com>'
subject="PREY -- status report"

# timelapse to watch for modified files, default one hour
minutos=60

# route where to get the modified files from
ruta_archivos=~/

# change wallpaper to alert nearby users -- EXPERIMENTAL!
alertwallpaper=n
wallpaper="alerts/prey-wallpaper-$lang.png"

# alert the user with a message, y or n
alertuser=n
alertmsg="This is a stolen computer, and has been marked by Prey.
Please contact immediately $emailtarget to clarify the situation.
Otherwise you'll be notified to the police. YOU HAVE BEEN WARNED!"

# should we kill the X session?  -- EXPERIMENTAL!
# this isn't such a good idea anyway, since we should try to keep
# the guy logged in for as long as we can, to get the maximum amount
# of information we can from him -- Tomas
killx=n

# where to store the temporary images
screenshot=/tmp/prey-screenshot.jpg
picture=/tmp/prey-picture.jpg


####################################################################
# not implemented yet
####################################################################

# backup ?
backup_path=~/.prey

# guest account to create so we can lurk him into logging in
guest_account=guest

# for how much time are we going to gather TCP packages?
tcpdump_time=100
