#!/bin/bash
####################################################################
# Prey Debian Preinstall Script - by Tomas Pollak (bootlog.org)
# URL : http://preyproject.com
# License: GPLv3
####################################################################

INSTALLPATH=/usr/share/prey

if [ -f $INSTALLPATH/config ]; then
	mv $INSTALLPATH/config $INSTALLPATH/config.backup
fi

exit 0
