#!/bin/bash
####################################################################
# PREY Location Module Windows Functions - by Tomas Pollak (bootlog.org)
# URL : http://preyproject.com
# License: GPLv3
####################################################################

function get_wifi_access_points {
	# $base_path/lib/wifi_config.exe -aps | sed 's/PUT_THE_MAGIC_IN_HERE//'
	echo ''
}
