#!/bin/bash
####################################################################
# PREY Report Module Config File - by Tomas Pollak (bootlog.org)
# URL : http://prey.bootlog.org
# License: GPLv3
####################################################################

# timelapse to watch for modified files, in minutes
modified_files_time=60

# route where to get the modified files from
modified_files_path=~/

# where to store the temporary images
screenshot=/tmp/prey-screenshot.jpg
picture=/tmp/prey-picture.jpg
