#!/bin/bash
####################################################################
# PREY Configuration File - by Tomas Pollak (bootlog.org)
# URL : http://prey.bootlog.org
# License: GPLv3
####################################################################

# change wallpaper to alert nearby users -- EXPERIMENTAL!
alertwallpaper=n
wallpaper="alerts/prey-wallpaper-$lang.png"

# alert the user with a message, y or n
alertuser=n
alertmsg="This is a stolen computer, and has been marked by Prey.
Please contact immediately $emailtarget to clarify the situation.
Otherwise you'll be notified to the police. YOU HAVE BEEN WARNED!"

