#!/bin/bash
####################################################################
# PREY Alert Module Configuration File - by Tomas Pollak (bootlog.org)
# URL : http://preyproject.com
# License: GPLv3
####################################################################

# alert the user with a message, y or n
alert_user=n
alert_message='This is a stolen computer, and has been marked by Prey.
You should contact us immediately at http://preyproject.com to clarify the situation.
Otherwise you"ll be notified to the police. Time is running: YOU HAVE BEEN WARNED!'

# change wallpaper to alert nearby users -- EXPERIMENTAL!
change_wallpaper=n
wallpaper="$module_path/lib/prey-wallpaper-$lang.png"

