#!/bin/bash
####################################################################
# Prey Alert Module - by Tomas Pollak (bootlog.org)
# URL: http://preyproject.com
# License: GPLv3
####################################################################

echo "$STRING_SHOW_ALERT"
alert_user

if [ $change_wallpaper == 'y' ]; then
	echo "$STRING_CHANGE_WALLPAPER"
	if [ ! -f "$wallpaper.orig" ]; then # we still havent put the email address
		put_email_on_wallpaper
	fi
	change_wallpaper
fi
