#!/bin/bash
####################################################################
# Prey Core Async Jobs Functions - by Tomas Pollak (bootlog.org)
# URL: http://preyproject.com
# License: GPLv3
####################################################################

enqueue_jobs(){
	STDOUT=$(echo -e "$requested_jobs")
	while read line; do

		local module=`echo "$line" | sed 's/.*module="\([a-z_]*\)".*/\1/'`
		local function=`echo "$line" | sed 's/.*function="\([a-z_]*\)".*/\1/'`
		add_job "$function" "$module"

	done <<< "$STDOUT"
}

callback(){
	until read -st 1; do
		echo -n ""
	done

	echo "Done. Running callback!"
	eval '$1 $REPLY'
}

add_job(){
	if [ -z "$current_module" ]; then
		current_module=$2
	fi
	echo " ++ Adding job for $current_module: $1"
	jobs[${#jobs[*]}]="${current_module}__${1}"
}

run_pending_jobs(){
	if [ "${#jobs[*]}" -gt 0 ]; then
		echo -e "\n${bold} -- Running pending jobs...${bold_end}\n"
		for j in "${jobs[@]}"
		do
			module=`echo $j | sed 's/__.*//g'`
			function=`echo $j | sed 's/.*__//g'`
			echo " -- Running job $function from $module module."
			function_exists $function
			if [ $? == 1 ]; then
				initialize_module "$module"
			fi
			eval "$function"
		done
	fi
}
