#!/bin/bash
####################################################################
# Prey Core On-Demand Functions - (c) 2010 Fork Ltd.
# URL: http://preyproject.com
# License: GPLv3
####################################################################

on_demand_command(){
	openssl s_client -no_ssl2 -nbio -quiet -connect $on_demand_host:$on_demand_port 2> /dev/null
	# log " -- OpenSSL returned. Removing pipe/lockfile..."
	rm -f "$on_demand_pipefile" 2> /dev/null
	kill_process "$on_demand_pipefile" &> /dev/null
}

on_demand_stdin(){
	tail -f "$on_demand_pipefile" 2> /dev/null
}

on_demand_loop(){
	on_demand_stdin | on_demand_command | while read data; do
		on_demand_process_msg "$data"
	done
}

on_demand_process_msg(){
	local data="$1"
	[ "$data" == "" ] && return 1
	# log " -- Got message: ${data}."
	local event=`get_json_val "$data" "event"`
	log " -- New event from Prey On-Demand Hub: ${event}"
	case "$event" in
		"ping")
			# log " -- Server pinged."
			last_pinged_at=`get_json_val "$data" 'timestamp'`
			;;
		"info")
			local message=`get_json_val "$data" "message"`
			log " -- Message from server: $message"
			;;
		"message")
			log ' -- Got message!'
			local message_type=`get_json_val "$data" "type"`
			if [ "$message_type" == "text" ]; then
				local message_body=`get_json_val "$data" 'body'`
				if [ "$message_body" == "run_once" ]; then
					"$base_path/prey.sh" --on-demand & disown -h
				else
					log " -- Unknown message: $message_body. Please update to latest version."
				fi
			else
				log " -- Unsupported message type: $message_type. Please update to latest version."
			fi
			;;
		*)
			log " -- Unknown event: ${event}. Please update to latest version."
			;;
	esac
}

enable_on_demand_mode(){
	if [ ! -f "$on_demand_pipefile" ]; then
		echo "" > "$on_demand_pipefile"
		on_demand_loop &
		local on_demand_pid=$!
		log " -- On Demand listener running with PID $on_demand_pid"
		sleep 2
		if [ -f "$on_demand_pipefile" ]; then
			log " -- On demand mode active!"
			on_demand_handshake
		else
			log " !! Coundn't set up on-demand mode."
		fi
	else
		log " -- Prey on demand is already running!"
	fi
}

on_demand_handshake(){
	local protocol_version=1
	log " -- Sending credentials to Prey On Demand Hub..."
	on_demand_send "{\"action\": \"connect\", \"data\": {\"client_version\": \"${version}\",\"key\":\"${device_key}\",\"group\":\"${api_key}\", \"protocol\": ${protocol_version} }}"
}

on_demand_ping(){
	local timestamp=$(date +%s)
	on_demand_send "{\"action\": \"ping\", \"data\": {\"key\":\"${device_key}\", \"timestamp\":${timestamp} }}"
}

on_demand_send(){
	echo "$1" >> "$on_demand_pipefile"
}
