#!/bin/bash
####################################################################
# Prey Core Setup Routine - by Tomas Pollak (bootlog.org)
# URL: http://preyproject.com
# License: GPLv3
####################################################################

readonly start_time=`date +"%F %T"`
os=`uname | sed "y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/"`
getter="curl -s"

if [ "$os" == "windowsnt" ]; then
	os=windows
	tmpdir="$WINDIR\Temp\x9125jx" # "random" name to make it harder to detect
	arch=`echo $PROCESSOR_ARCHITEW6432`
	if [ `find_in "$arch" '64'` ]; then
		echo -e " ** 64 bit architecture detected!"
		readonly 64bit=1 # so we can check later
		getter="curl64 -s"
	fi
else
	if [ "$os" == "darwin" ]; then
		os=mac
	fi
	tmpdir="/tmp/x9125jx"
fi

readonly control_panel_url="http://control.preyproject.com"
readonly updates_url="http://cloud.github.com/downloads/tomas/prey"
readonly modules_url=$control_panel_url
readonly getter
readonly tmpdir
readonly os
readonly user_agent="-A Prey/$version ($os)"
