#!/bin/bash
####################################################################
# Prey Core Setup Routine - by Tomas Pollak (bootlog.org)
# URL: http://preyproject.com
# License: GPLv3
####################################################################

if [ "$1" == "-t" ]; then
	echo -e "\n\033[1m -- TEST MODE ENABLED.\033[0m"
	. $base_path/test/include 2> /dev/null
	test_mode=1
fi

readonly start_time=`date +"%F %T"`
os=`lowercase \`uname\``
getter="curl -s"

if [ "$os" == "windowsnt" ]; then
	os=windows
	tmpdir="$base_path\platform\windows\etc\p${RANDOM}" # "random" name to make it harder to detect
	arch=`echo $PROCESSOR_ARCHITEW6432`
	if [ `find_in "$arch" '64'` ]; then
		echo -e " ** 64 bit architecture detected!"
		readonly x64=1 # so we can check later
		getter="curl64 -s"
	fi
	readonly logged_user=`whoami`
	readonly line_breaker="\r\n"
else
	if [ "$os" == "darwin" ]; then
		os=mac
	fi
	tmpdir="/tmp/p${RANDOM}"
	readonly line_breaker="\n"
	readonly logged_user=`who | cut -d' ' -f1 | sort -u | tail -1`
fi

readonly control_panel_url="http://control.preyproject.com" 2> /dev/null
readonly updates_url="http://cloud.github.com/downloads/tomas/prey" 2> /dev/null
readonly modules_url=$control_panel_url 2> /dev/null
readonly getter
readonly tmpdir
readonly os
readonly user_agent="-A Prey/$version ($os)"
