#!/bin/bash
####################################################################
# PREY Webcam Module Mac Functions - by Tomas Pollak (bootlog.org)
# URL : http://preyproject.com
# License: GPLv3
####################################################################

function take_picture {

	LOGINWINDOW_PID=`killall -s loginwindow | sed  's/.*[^0-9]//'`
	if [ "$LOGINWINDOW_PID" = "" ]
	then
		$module_path/lib/isightcapture $picture 2> /dev/null
	else
		launchctl bsexec $LOGINWINDOW_PID $module_path/lib/isightcapture $picture 2> /dev/null
	fi
}

function capture_video {

	echo ' !! Feature still in development!'

}
