#!/bin/bash
####################################################################
# PREY Webcam Module Linux Functions - by Tomas Pollak (bootlog.org)
# URL : http://preyproject.com
# License: GPLv3
####################################################################

function take_picture {

	# do we have streamer installed ?
	streamer=`which streamer`
	if [ -n "$streamer" ]; then

		$streamer -o /tmp/imagen.jpeg &> /dev/null # streamer necesita que sea JPEG (con la E) para detectar el formato

		if [ -e '/tmp/imagen.jpeg' ]; then

			mv /tmp/imagen.jpeg $picture > /dev/null

		else # by Vanscot, http://www.hometown.cl/ --> some webcams are unable to take JPGs so we grab a PPM

			$streamer -o /tmp/imagen.ppm &> /dev/null
			if [ -e '/tmp/imagen.ppm' ]; then

				convert=`which convert`
				if [ -n "$convert" ]; then # lets convert it to JPG if we have imagemagick installed
					$convert /tmp/imagen.ppm $picture > /dev/null
				else # lets just send it as a PPM
					picture='/tmp/imagen.ppm'
				fi

			fi

		fi

	fi
}

function capture_video {

	# we should already know if we do have streamer
	if [ -n "$streamer" ]; then

		frames=$(( $video_capture_time * $frames_per_second ))
		$streamer -o $video -f yuv2 -F stereo -r $frames_per_second -t $frames

	fi

}
