#!/bin/bash
####################################################################
# PREY Webcam Module Windows Functions - by Tomas Pollak (bootlog.org)
# URL: http://preyproject.com
# License: GPLv3
####################################################################

picture="c:\windows\temp\prey-picture.jpg"

function take_picture {

	# $module_path/lib/simplecapture.exe /filename $picture /suffix ' ' /jpgquality 80 /imgperfect 500 /imgcaption hh:nn:ss
	$module_path/lib/webcam_capture.exe
	$base_path/lib/bmp2png.exe $module_path/lib/vfw-0.bmp
	mv $module_path/lib/vfw-0.png "$picture"

}

function capture_video {

	echo ' !! Video capture still in development!'

}
