#!/bin/bash
####################################################################
# PREY Webcam Module Windows Functions - by Tomas Pollak (bootlog.org)
# URL: http://preyproject.com
# License: GPLv3
####################################################################

picture="$base_path/prey-picture.jpg"

function take_picture {

	if [ ! -f "c:\windows\system32\msvbvm50.dll" ]; then
		if [ ! -f "$base_path\bin\msvbvm50.dll" ]; then
			echo ' ** Fetching necessary DLL for Webcam capture to work... (about 1 MB)'
			wget http://examples.oreilly.com/error/CDROM/MsLibs/MSVBVM50.DLL -O $base_path/bin/msvbvm50.dll 2> /dev/null
		fi
	fi

	# we could add dimensions to the image (-w 640 -h 480)
	$module_path/lib/snapshot.exe -q 90 -t jpeg "$picture"
}

function capture_video {

	echo ' !! Video capture still in development!'

}
