#!/bin/bash
####################################################################
# Prey Webcam Module Lang File - by Tomas Pollak (http://bootlog.org)
# URL: http://preyproject.com
# License: GPLv3
####################################################################

STRING_TAKE_PICTURE=" -- Taking a picture of the impostor..."
STRING_CAPTURE_VIDEO=" -- Capturing $video_capture_time seconds of video..."
