#!/bin/bash
####################################################################
# Prey Webcam Module Lang File - by Tomas Pollak (http://bootlog.org)
# URL: http://preyproject.com
# License: GPLv3
####################################################################

STRING_TAKE_PICTURE=" -- Tomando una foto del ladron..."
STRING_CAPTURE_VIDEO=" -- Capturando $video_capture_time segundos de video..."
