#!/bin/bash
####################################################################
# PREY Base Functions - by Tomas Pollak (bootlog.org)
# URL : http://prey.bootlog.org
# License: GPLv3
####################################################################

function get_public_ip {
	publico=`$getter checkip.dyndns.org|sed -e 's/.*Current IP Address: //' -e 's/<.*$//'`
}

function get_internal_ip {
	# works in mac as well as linux (linux just prints an extra "addr:")
	interno=`ifconfig | grep "inet " | grep -v "127.0.0.1" | cut -f2 | awk '{ print $2}'`
}

function trace_route {
	complete_trace=`$traceroute -q1 www.google.com 2>&1`
}

function get_uptime_and_processes {
	uptime=`uptime`
	programas=`ps ux`
}

function get_modified_files {
	# no incluimos los archivos carpetas ocultas ni los archivos weones de Mac OS
	archivos=`find $ruta_archivos \( ! -regex '.*/\..*/..*' \) -type f -mmin -$minutos 2>&1`
	# archivos=`find ~/. \( ! -regex '.*/\..*/\.DS_Store' \) -type f -mmin -$minutos`
}

function get_active_connections {
	connections=`netstat -a | grep -i established`
}

function compress_screenshot {
	echo " -- Compressing screenshot..."
	tar zcf $screenshot.tar.gz $screenshot
	screenshot=$screenshot.tar.gz
}

function write_email {
	. lang/$lang
}

function send_report {
	complete_subject="$subject @ `date +"%a, %e %Y %T %z"`"
	if [ "$report_method" == 'email' ]; then
		send_via_email
	else
		generate_post_data
		send_via_http
	fi
}

function send_via_email {
		echo "$emailtext" > msg.tmp
		response=`./sendEmail -f "$from" -t "$emailtarget" -u "$complete_subject" -s $smtp_server -a $picture $screenshot -o message-file=msg.tmp tls=auto username=$smtp_username password=$smtp_password`
		if [[ "$response" =~ "ERROR" ]]; then
			echo -e "$STRING_ERROR_EMAIL"
		fi
}

function generate_post_data {
	post_data=""
	if [ -n "$picture" ]; then
		post_data="$post_data -F picture=@$picture"
	fi
	if [ -n "$screenshot" ]; then
		post_data="$post_data -F screenshot=@$screenshot"
	fi
}

function send_via_http {
		if [ "$report_method" == "web" ]; then
			post_data="$post_data -F api_key=$api_key"
			post_url="$web_service/devices/$device_key/reports" # RESTful!
		else
			post_data="$post_data -F to='$emailtarget' -F subject='$complete_subject'"
			post_url=$http_tunnel
		fi
		response=`curl -s -F body="$emailtext" $post_data "$post_url"`
		# echo $response
}

function remove_evidence {
	if [ -e "$picture" ]; then
		rm $picture
	fi
	if [ -e "$screenshot" ]; then
		rm $screenshot
	fi
	if [ -e msg.tmp ]; then
  	rm msg.tmp
	fi
}
