#!/bin/bash
####################################################################
# PREY Darwin (Mac) Base Functions - by Tomas Pollak (bootlog.org)
# URL : http://prey.bootlog.org
# License: GPLv3
####################################################################

function try_to_connect {
	# restart airport service
	networksetup -setnetworkserviceenabled AirPort off 2>/dev/null
	networksetup -setnetworkserviceenabled AirPort on 2>/dev/null

	# power on the airport
	networksetup -setairportpower off 2>/dev/null
	networksetup -setairportpower on 2>/dev/null

	# list available access points and parse to get first SSID with security "NONE"
	essid=`$airport -s | grep NONE | head -1 | cut -c1-33 | sed 's/^[ \t]*//'`

	if [ -n "$essid" ]; then

		# now lets connect and get the new info
		networksetup -setairportnetwork $essid 2>/dev/null
		wifi_info=`$airport -I | grep -v "Off"`

	fi
}

