#!/bin/bash
####################################################################
# PREY Windows Base Functions - by Tomas Pollak (bootlog.org)
# URL: http://preyproject.com
# License: GPLv3
####################################################################

function get_gateway_ip {
	gateway_ip=`ipconfig | grep Gateway | sed 's/^.*: //g' | grep -v '^$' | head -1`
}

function try_to_connect {
	# netsh wlan connect name=Profile2 ssid=SSID2 interface="Wireless Network Connection"
	echo ' !! Autoconnect in Windows still in development. Thanks for your patience!'
}

# TODO: Finish this!
function get_current_delay {
	schtasks.exe -query -fo LIST | grep "Modifier"
}

function update_execution_delay {
	schtasks.exe -change -tn "Prey" -sc MINUTE -mo $delay
}

# module de/activation functions

function is_module_active {
	cat $base_path/modules/$1/active 2> /dev/null
}

function activate_module {
	touch $base_path/modules/$1/active
	echo 1 > $base_path/modules/$1/active
}

function deactivate_module {
	# echo 0 > $base_path/modules/$1/active
	rm $base_path/modules/$1/active 2> /dev/null
}

function deactivate_all_modules {
	for file in `find $base_path/modules -name active`; do
		# echo 0 > $file
		rm $file
	done
}
