#!/bin/bash
####################################################################
# PREY Windows Base Functions - by Tomas Pollak (bootlog.org)
# URL: http://preyproject.com
# License: GPLv3
####################################################################

function get_gateway_ip {
	gateway_ip=`ipconfig | grep Gateway | sed 's/^.*: //g' | grep -v '^$' | head -1`
}

function try_to_connect {
	# netsh wlan connect name=Profile2 ssid=SSID2 interface="Wireless Network Connection"
	echo ' !! Autoconnect in Windows still in development/testing mode. Thanks for your patience!'
}

function get_current_delay {
	delay_in_miliseconds=`cat $base_path/delay`
	echo $(($delay_in_miliseconds/60000))
}

function update_execution_delay {
	delay_in_miliseconds=$(($delay*60*1000))
	echo "$delay_in_miliseconds" > $base_path/delay
}

# module de/activation functions

function is_module_active {
	cat $base_path/modules/$1/active 2> /dev/null
}
