#!/bin/bash
####################################################################
# Prey Network Module - by Tomas Pollak (bootlog.org)
# URL: http://preyproject.com
# License: GPLv3
####################################################################

echo "$STRING_GET_IP"
get_public_ip
add_trace public_ip $public_ip

echo "$STRING_GET_LAN_IP"
get_internal_ip
add_trace internal_ip $internal_ip

echo "$STRING_GET_MAC_AND_WIFI"
get_mac_address
add_trace mac_address $mac_address

get_wifi_info
if [ -n "$wifi_info" ]; then
	add_trace wifi_info "$wifi_info"
fi

if [ "$trace_route" == 'y' ]; then
	echo "$STRING_TRACE"
	trace_route
fi
