#!/bin/bash
####################################################################
# PREY Darwin (Mac) Base Functions - by Tomas Pollak (bootlog.org) and Diego Torres (warorface.com)
# URL : http://preyproject.com
# License: GPLv3
####################################################################

readonly logged_pid=`ps -ax | grep loginwindow.app | grep -v grep | awk '{print $1}'`
readonly airport='/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport'

file_size(){
	ls -l "$1" | cut -f8 -d " "
}

get_gateway_ip() {
	gateway_ip=`netstat -rn | grep default | cut -c20-35`
}

get_wifi_info() {
	wifi_info=`$airport -I | grep -v "Off"`
}

try_to_connect() {
	# restart airport service
	networksetup -setnetworkserviceenabled AirPort off 2>/dev/null
	networksetup -setnetworkserviceenabled AirPort on 2>/dev/null

	# power on the airport
	networksetup -setairportpower off 2>/dev/null
	networksetup -setairportpower on 2>/dev/null

	# list available access points and parse to get first SSID with security "NONE"
	essid=`$airport -s | grep NONE | head -1 | cut -c1-33 | sed 's/^[ \t]*//'`

	if [ -n "$essid" ]; then

		networksetup -setairportnetwork $essid 2>/dev/null

	fi
}

get_current_delay() {
	delay_in_secs=`grep "integer" /Library/LaunchDaemons/com.prey.agent.plist | sed 's/[^0-9]//g'`
	delay_in_mins=$((delay_in_secs/60))
	echo $delay_in_mins
}

update_execution_delay() {
	delay_in_secs=$((delay*60))
	launchctl stop com.prey.agent
	sed -i -e "s/<integer>.*<\/integer>/<integer>$delay_in_secs<\/integer>/" /Library/LaunchDaemons/com.prey.agent.plist
	launchctl start com.prey.agent
}
