#!/bin/bash
####################################################################
# Prey Mac Specific Functions - by Tomas Pollak (bootlog.org) and Diego Torres (warorface.com)
# URL : http://preyproject.com
# License: GPLv3
####################################################################

run_as_current_user(){
	if [ "`whoami`" == "root" ]; then
		launchctl bsexec $logged_pid $1
	else
		$1
	fi
}

get_gateway_ip() {
	if [ -z "$gateway_ip" ]; then
		netstat=`which netstat`
		if [ -n "$netstat" ]; then
			gateway_ip=`$netstat -rn | grep default | cut -c20-35`
		fi
	fi
}

get_wifi_info() {
	wifi_info=`$airport -I | grep -v "Off"`
}

try_to_connect() {
	# restart airport service
	networksetup -setnetworkserviceenabled AirPort off 2>/dev/null
	networksetup -setnetworkserviceenabled AirPort on 2>/dev/null

	# power on the airport
	networksetup -setairportpower off 2>/dev/null
	networksetup -setairportpower on 2>/dev/null

	# list available access points and parse to get first SSID with security "NONE"
	essid=`$airport -s | grep NONE | head -1 | cut -c1-33 | sed 's/^[ \t]*//'`

	if [ -n "$essid" ]; then

		networksetup -setairportnetwork $essid 2>/dev/null

	fi
}

############################################
# updater-specific functions
############################################

# check permissions, whatever goes here
pre_update_check(){
	log ' -- All set!'
	return 0
}

# check plist, shutdown task
pre_update_hook(){
	return 0
}

# post update hooks go in here
post_update_hook(){
	log ' -- Reloading Prey...'
	$base_path/prey.sh & # lets restart prey now
}

############################################
# Device creation parameters
############################################
get_pc_info(){
	pc_name=`system_profiler SPSoftwareDataType | grep 'Computer Name' | sed 's/.*: //g'`
	local pc_os_number=`sw_vers -productVersion | cut -c1-4`

	if [ $pc_os_number == "10.6" ]; then
		pc_os_version="snow-leopard"
	elif [ $pc_os_number == "10.5" ]; then
		pc_os_version="leopard"
	else
		pc_os_version="tiger"
	fi
	local is_macbook=`system_profiler SPHardwareDataType | grep -i 'macbook'`
	if [ -z "$is_macbook" ]; then
		pc_type="Desktop"
	else
		pc_type="Portable"
	fi

}
