#!/bin/bash
###################################################################
# Prey Mac Specific Settings - by Tomas Pollak (bootlog.org)
# URL: http://preyproject.com
# License: GPLv3
####################################################################

readonly logged_user=$(stat /dev/console | cut -d' ' -f5)
readonly logged_pid=`ps aux | awk -v Var=${logged_user} '/loginwindow.app/ && match(Var,$1) { print $2 }'`

readonly system_path="/Library"
readonly users_path="/Users"
readonly programs_path="/Applications"

readonly launchd_trigger_label="com.prey.trigger"

readonly airport='/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport'

get_osx_version(){

	local pc_os_number=`sw_vers -productVersion | cut -c1-4`

	if [[ $pc_os_number == "10.7" || `is_greater_than "$pc_os_number" 10.7` == 1 ]]; then
		osx_version="lion"
	elif [[ $pc_os_number == "10.6" || `is_greater_than "$pc_os_number" 10.6` == 1 ]]; then
		osx_version="snow-leopard"
	elif [[ $pc_os_number == "10.5" || `is_greater_than "$pc_os_number" 10.5` == 1 ]]; then
		osx_version="leopard"
	elif [[ $pc_os_number == "10.4" || `is_greater_than "$pc_os_number" 10.4` == 1 ]]; then
		osx_version="tiger"
	else
		osx_version="unknown"
	fi

}

get_osx_version
