#!/bin/bash
###################################################################
# Prey Mac Specific Settings - by Tomas Pollak (bootlog.org)
# URL: http://preyproject.com
# License: GPLv3
####################################################################

readonly logged_user=$(stat /dev/console | cut -d' ' -f5)
readonly logged_pid=`ps aux | awk -v Var=${logged_user} '/loginwindow.app/ && match(Var,$1) { print $2 }'`

readonly system_path="/Library"
readonly users_path="/Users"
readonly programs_path="/Applications"

readonly launchd_trigger_label="com.prey.trigger"

readonly airport='/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport'

get_osx_version(){

	local pc_os_number=$(sw_vers -productVersion)
	osx_version="$pc_os_number"

	if [[ `is_greater_than "$pc_os_number" 10.9` == 1 ]]; then
		osx_version_name="mavericks"
	elif [[ `is_greater_than "$pc_os_number" 10.8` == 1 ]]; then
		osx_version_name="mountain-lion"
	elif [[ `is_greater_than "$pc_os_number" 10.7` == 1 ]]; then
		osx_version_name="lion"
	elif [[ `is_greater_than "$pc_os_number" 10.6` == 1 ]]; then
		osx_version_name="snow-leopard"
	elif [[ `is_greater_than "$pc_os_number" 10.5` == 1 ]]; then
		osx_version_name="leopard"
	elif [[ `is_greater_than "$pc_os_number" 10.4` == 1 ]]; then
		osx_version_name="tiger"
	else
		osx_version_name="unknown"
	fi

}

get_osx_version