#!/bin/bash
####################################################################
# Prey - by Tomas Pollak (http://bootlog.org)
# English lang file v 0.2 - by Juan C. Mardones (http://juanmardones.com)
# URL : http://prey.bootlog.org
# License: GPLv3
####################################################################

texto="
Good news my friend, it seems we found it!

General state of computer (uptime)
--------------------------------------------------------------------
$uptime

Connection information
--------------------------------------------------------------------
IP Publico: $publico. IP interno: $interno.

Route information
--------------------------------------------------------------------
Direccion MAC: $mac. Gateway: $routes

WiFi information
--------------------------------------------------------------------
$wifi_info

In the last $minutos minutes the following files have been modified
--------------------------------------------------------------------
$archivos

Running programs
--------------------------------------------------------------------
$programas

Open connections
--------------------------------------------------------------------
$connections


Now, go catch the bastard!

--
Your humble servant, Prey
For updates visit http://prey.bootlog.org
"

STRING_START="\n ### PREY $version spreads its wings!\n"
STRING_CHECK_URL=" -- Checking URL..."
STRING_PROBLEM=" -- HOLY GUACAMOLE!!"
STRING_NO_PROBLEM=" -- Nothing to worry about. :)\n"
STRING_GET_IP=" -- Getting public IP address..."
STRING_GET_LAN_IP=" -- Getting private LAN IP address..."
STRING_GET_MAC_AND_WIFI=" -- Getting MAC address, routing and Wifi info..."
STRING_TRY_TO_CONNECT=" -- Trying to connect to first open wifi network available..."
STRING_NO_CONNECT_TO_WIFI=" -- Couldn't find a way to connect to an open wifi network!"
STRING_TRACE=" -- Tracing our complete route to the Internet..."
STRING_UPTIME_AND_PROCESS=" -- Getting computer uptime and a list of running programs..."
STRING_MODIFIED_FILES=" -- Getting a list of recently modified files..."
STRING_ACTIVE_CONNECTIONS=" -- Getting list of current active connections..."
STRING_WRITE_EMAIL=" -- Writing our email..."
STRING_TAKE_IMAGE=" -- Taking a screenshot and a picture of the impostor..."
STRING_TAKE_IMAGE_DONE=" -- Done with the images!"
STRING_SENDING_EMAIL=" -- Sending the email..."
STRING_ERROR_EMAIl="There was a problem sending the email. Are you sure it was setup correctly?
If you're using Gmail, try removing the '@gmail.com' from the smtp_username field in Prey's config file."
STRING_REMOVE_EVIDENCE=" -- Removing all traces of evidence..."
STRING_CHANGE_WALLPAPER=" -- Changing the wallpaper to alert him and nearby users..."
STRING_SHOW_ALERT=" -- Showing the guy our alert message..."
STRING_XKILL=" -- Kicking him off the X session!"
STRING_DONE=" -- Done! Happy hunting! :)\n"
STRING_MACKILL="How do we shut him off in Mac OS?"
