#!/bin/bash
####################################################################
# Prey - by Tomas Pollak (http://bootlog.org)
# Spanish language file v 0.2 - by Juan C. Mardones (http://juanmardones.com)
# URL : http://prey.bootlog.org
# License: GPLv3
####################################################################

if [ -n "$DEFAULT_INSTALLPATH" ]; then # we're running the installer

	# installer messages
	# TODO: translate this to spanish

	HELLO_IN_LANGUAGE=" -- Prey hablara espanol entonces!"
	WHERE_TO_INSTALL_PREY=" -> Donde quieres que instalemos Prey? [$DEFAULT_INSTALLPATH] "
	USING_DEFAULT_INSTALL_PATH=" -- Usando la ruta de instalacion por defecto..."
	INVALID_INSTALL_PATH=" !! Ruta invalida de instalacion. La carpeta superior no existe!\n"
	SETTING_INSTALL_PATH=" -- Ok, instalaremos Prey en $INSTALLPATH."

	DELETING_OLD_FILES=" -- Eliminando archivos antiguos de Prey...\n"
	CONFIG_FILE_EXISTS=" -> Archivo de configuracion existe! Quieres que nos saltemos las preguntas de configuracion? (No recomendado) [n] "

	SKIP_INSTALL_QUESTIONS=" -- Muy bien, solo actualizaremos los archivos necesarios!\n"

	# TODO: finish translating this.
	DEFINE_REPORT_METHOD=" -> Which reporting method would you like to use? (email, tunnel, web) [email] "
	DEFAULT_REPORT_METHOD=" -- Using email as our reporting method. All good!"
	ADD_API_KEY=" -> Please enter the 12-digit API Key as supplied by the web service: "
	INVALID_API_KEY=" !! Invalid API key! Remember to signup at preyproject.com to get one.\n"
	ADD_DEVICE_KEY=" -> Please enter the six-digit Device Key as supplied by the web service."
	INVALID_DEVICE_KEY=" !! Invalid device key! Remember to register your device in preyproject.com to get one."

	USING_DEFAULT_APP_URL=" -- Using routes for the web application. Nothing to write in here!"

	ENTER_EMAIL_ADDRESS=" -> A que casilla de email quieres que Prey envie el correo? (i.e. casilla@dominio.com) [] "
	INVALID_EMAIL_ADDRESS=" !! Necesitas escribir una casilla de correo valida! Saliendo...\n"

	ENTER_SMTP_SERVER=" -> Que servidor SMTP quieres que usemos? (con su puerto) [smtp.gmail.com:587] "
	DEFAULT_SMTP_SERVER=" -- Usando Gmail como servidor STMP. "
	ENTER_SMTP_USER=" -> Escribe tu nombre de usuario del servidor SMTP: (i.e. casilla@gmail.com)"
	DEFAULT_SMTP_USER=" -- Nuestro usuario STMP sera entonces"
	ENTER_SMTP_PASS=" -> Escribe tu contrasena para el servidor SMTP: (No va a mostrar nada) [] "
	INVALID_SMTP_PASS=" !! Debes escribir una contrasena SMTP valida. Saliendo...\n"

	CHECK_URL_OR_NOT=" -- Quieres que Prey use una URL de verificacion? (No significa que el reporte se enviara cada vez que Prey se ejecute) [n] "
	ENTER_URL=" -- Ok, que URL quieres usar entonces? [i.e. http://miservidor.com/laptop_desaparecido] "
	INVALID_URL=" !! Tienes que definir una URL. Saliendo...\n"
	SET_TIMING=" -- Ok, la ultima. Con que frecuencia (en minutos) quieres que Prey se ejecute? [$TIMING] "

	INSTALLING_SOFTWARE=" -- Ok, instalando el software necesario...\n"
	COPYING_ISIGHTCAPTURE=" -- Copiando iSightCapture a $INSTALLPATH..."
	COPYING_FILES="\n -- Copiando archivos necesarios a $INSTALLPATH y definiendo permisos..."
	ADDING_CRONTAB=" -- Agregando entrada en el crontab..."
	INSTALL_OK="\033[1m\n -- Todo bien! Prey esta instalado y listo para volar. Ahora puedes eliminar esta carpeta.
 -- Si alguna vez quieres desinstalar Prey, basta con que elimines la carpeta $INSTALLPATH
    y remuevas la linea de Prey del crontab de root:\n
\t $ sudo rm -Rf $INSTALLPATH\n \t $ sudo crontab -l | grep -v prey | sudo crontab -\n
 -- Para actualizaciones recuerda visitar http://prey.bootlog.org!\033[0m\n\n"

else # prey status messages

	STRING_START="\n ### PREY $version despliega sus alas!\n"
	STRING_TRY_TO_CONNECT=" -- Intentando conectarnos a la primera red abierta disponible..."
	STRING_NO_CONNECT_TO_WIFI=" -- No encontramos la forma de conectarnos a una red Wifi abierta!"
	STRING_CHECK_URL=" -- Revisando URL..."
	STRING_PROBLEM=" -- OUCH!!"
	STRING_NO_PROBLEM=" -- Nada de que preocuparse. :)\n"
	STRING_DONE=" -- Todo listo! Suerte con la caceria! :)\n"

fi
