#!/bin/bash
####################################################################
# Prey - by Tomas Pollak (http://bootlog.org)
# Spanish language file v 0.2 - by Juan C. Mardones (http://juanmardones.com)
# URL : http://preyproject.com
# License: GPLv3
####################################################################

STRING_START="\n ### PREY $version despliega sus alas!\n"
STRING_TRY_TO_CONNECT=" -- Intentando conectarnos a la primera red abierta disponible..."
STRING_NO_CONNECT_TO_WIFI=" -- No encontramos la forma de conectarnos a una red Wifi abierta!"
STRING_CHECK_URL=" -- Revisando URL..."
STRING_NO_PROBLEM=" -- Nada de que preocuparse. :)\n"
STRING_PROBLEM=" -- OUCH!!"
STRING_WRITE_EMAIL=" -- Redactando el reporte..."
STRING_SENDING_EMAIL=" -- Enviando el reporte..."
STRING_ERROR_EMAIL="\n\033[1m !! Hubo un problema enviando el correo electronico. ¿Estas seguro de que fue configurado correctamente?
	Si estas usando Gmail, intenta removiendo el '@gmail.com' del campo smtp_username en el archivo de configuracion.\033[0m\n"
STRING_REMOVE_EVIDENCE=" -- Eliminando la evidencia..."
STRING_DONE=" -- Todo listo! Suerte con la caceria! :)"

EMAIL_HEADER="Buenas noticias amigo mio, al parecer lo encontramos!\n\nAqui va el reporte de tu computador:\n\n"
EMAIL_FOOTER="\n\nSuerte con la caceria!\n\n--\nTu fiel servidor, Prey\nhttp://preyproject.com"
