#!/bin/bash
####################################################################
# Prey - by Tomas Pollak (http://bootlog.org)
# Spanish language file v 0.2 - by Juan C. Mardones (http://juanmardones.com)
# URL : http://prey.bootlog.org
# License: GPLv3
####################################################################

texto="
Buenas noticias amigo mio, al parecer lo encontramos!

Estado general del computador (uptime)
--------------------------------------------------------------------
$uptime

Datos de conexion
--------------------------------------------------------------------
IP Publico: $publico. IP interno: $interno.

Enrutado de red
--------------------------------------------------------------------
Direccion MAC: $mac. Gateway: $routes

Datos sobre red WiFi
--------------------------------------------------------------------
$wifi_info

En los ultimos $minutos minutos se han modificado estos archivos
--------------------------------------------------------------------
$archivos

Programas en execucion
--------------------------------------------------------------------
$programas

Conexiones abiertas
--------------------------------------------------------------------
$connections


Ahora a agarrar al maldito!

--
Tu fiel servidor, Prey
Para actualizaciones visita http://prey.bootlog.org
"

STRING_START="\n ### PREY $version spreads its wings!\n"
STRING_CHECK_URL=" -- Revisando URL..."
STRING_PROBLEM=" -- Oh mi Dios!!"
STRING_NO_PROBLEM=" -- Nada de que preocuparse. :)\n"
STRING_GET_IP=" -- Obteniendo la direccion IP publica..."
STRING_GET_LAN_IP=" -- Obteniendo la direccion IP privada de la LAN..."
STRING_GET_MAC_AND_WIFI=" -- Obteniendo direccion MAC, tabla de rutas e informacion de la Red Wifi..."
STRING_TRY_TO_CONNECT=" -- Intentando conectarse a la primera red abierta disponible..."
STRING_NO_CONNECT_TO_WIFI=" -- No se pudo encontrar una manera de conectarse a una red abierta Wifi!"
STRING_TRACE=" -- Traceando la ruta completa hacia Internet..."
STRING_UPTIME_AND_PROCESS=" -- Obteniendo el uptime y la lista de programas en ejecucion..."
STRING_MODIFIED_FILES=" -- Obteniendo una lista de los archivos recientemente modificados..."
STRING_ACTIVE_CONNECTIONS=" -- Obteniendo la lista de las conecciones activas..."
STRING_WRITE_EMAIL=" -- Escribiendo el correo electronico..."
STRING_TAKE_IMAGE=" -- Tomando una captura de pantalla y una foto de la persona que se encontro el computador..."
STRING_TAKE_IMAGE_DONE=" -- Finanlizando la captura de imagenes."
STRING_SENDING_EMAIL=" -- Enviando el correo electronico."
STRING_ERROR_EMAIl="Se encontro un problema enviando el correo electronico. ¿Estas seguro de que fue configurado correctamente?
Si estas usando Gmail, intenta con remover la '@gmail.com' del campo smtp_username en el archivo de configuracion."
STRING_REMOVE_EVIDENCE=" -- Removiendo todos la evidencia."
STRING_CHANGE_WALLPAPER=" -- Cambiando el wallpaper para alertar a la persona y a los que esten cerca..."
STRING_SHOW_ALERT=" -- Mostrando nuestro mensaje de alerta..."
STRING_XKILL=" -- Intentando sacarlo de la session X!"
STRING_MACKILL="Como se supone que realizamos esto en Mac OS?"
STRING_DONE=" -- Listo, y suerte! :)\n"
