#!/bin/bash
####################################################################
# Prey - by Tomas Pollak (http://bootlog.org)
# Swedish lang file v 0.2 - by Mikael Hiort af Ornäs (mikael.hafo@hotmail.com)
# Latest review: 2014-11-14
# Contributors: Dan Sellberg (v 0.1)
# URL : http://preyproject.com
# License: GPLv3
####################################################################

STRING_START="PREY $version vecklar ut sina vingar!"
STRING_TRY_TO_CONNECT=" -- Försöker ansluta till första tillgängliga trådlösa nätverk …"
STRING_NO_CONNECT_TO_WIFI=" -- Det gick inte att ansluta till något trådlöst nätverk!"
STRING_CHECK_URL=" -- Kontrollerar URL …"
STRING_NO_PROBLEM=" -- Inget att oroa sig över. :)\n"
STRING_PROBLEM=" -- Ojsan!!"
STRING_WRITE_EMAIL=" -- Skriver vårt e-postmeddelande …"
STRING_SENDING_EMAIL=" -- Skickar rapporten …"
STRING_ERROR_EMAIL="\n\033[1m !! Det uppstod ett problem när e-postmeddelandet skulle skickas. Är du säker på att du angav korrekta e-postuppgifter?
Om du använder Gmail kan du testa att ta bort '@gmail.com' från fältet 'smtp_username' i Preys konfigurationsfil.\033[0m\n"
STRING_REMOVE_EVIDENCE=" -- Tar bort alla spår av installationsprocessen …"
STRING_DONE=" -- Klart! God jaktlycka! :)"

EMAIL_NOTICE=""
EMAIL_HEADER="Goda nyheter, det verkar som att vi har hittat den.\n\nHär är rapporten från din dator:\n\n"
EMAIL_FOOTER="\n\nKontroll av URL: ${check_url}\n\nGod jaktlycka!\n\n--\nDin ödmjuka tjänare, Prey\nhttp://preyproject.com"
