#!/bin/bash
####################################################################
# Prey - by Tomas Pollak (http://bootlog.org)
# Swedish lang file v 0.2 - by Mikael Hiort af Ornäs
# URL : http://preyproject.com
# License: GPLv3
####################################################################

STRING_START="PREY $version vecklar ut sina vingar!"
STRING_TRY_TO_CONNECT=" -- Försöker ansluta till första tillgängliga trådlösa nätverk ..."
STRING_NO_CONNECT_TO_WIFI=" -- Det gick inte att ansluta till ett öppet trådlöst nätverk!"
STRING_CHECK_URL=" -- Kontrollerar URL ..."
STRING_NO_PROBLEM=" -- Ingenting att oroa sig över. :)\n"
STRING_PROBLEM=" -- JÖSSES!!"
STRING_WRITE_EMAIL=" -- Skriver vårt e-brev ..."
STRING_SENDING_EMAIL=" -- Skickar rapporten ..."
STRING_ERROR_EMAIL="\n\033[1m !! Det uppstod ett problem när e-brevet skulle skickas. Är du säker på att alla uppgifter angavs korrekt?
Om du använder Gmail kan du försöka att ta bort '@gmail.com' frrån fältet smtp_username i Preys konfigurationsfil.\033[0m\n"
STRING_REMOVE_EVIDENCE=" -- Tar bort alla spår av aktivitet ..."
STRING_DONE=" -- Klart! God jaktlycka! :)"

EMAIL_NOTICE=""
EMAIL_HEADER="Goda nyheter! Det verkar som om vi har hittat den.\n\nHär är rapporten från din dator:\n\n"
EMAIL_FOOTER="\n\nKontrollerad URL: ${check_url}\n\nGod jaktlycka!\n\n--\nMed vänliga hälsningar, Prey\nhttp://preyproject.com"
