#!/bin/bash
###################################################################
# PREY Windows Base Functions - by Tomas Pollak (bootlog.org)
# URL: http://preyproject.com
# License: GPLv3
####################################################################

readonly unzip_exlude='-x \*linux* -x \*darwin*'

get_gateway_ip() {
	gateway_ip=`ipconfig | grep Gateway | sed 's/^.*: //g' | grep -v '^$' | head -1`
}

try_to_connect() {
	# netsh wlan connect name=Profile2 ssid=SSID2 interface="Wireless Network Connection"
	echo ' !! Autoconnect in Windows still in development/testing mode. Thanks for your patience!'
}

get_current_delay() {
	local delay_in_miliseconds=`reg query "HKLM\Software\Prey" //v "Delay" | grep Delay | sed "s/[^0-9]*//"`
	echo $(($delay_in_miliseconds/60000))
}

update_execution_delay() {
	local delay_in_miliseconds=$(($1*60*1000))
	reg add "HKLM\Software\Prey" //v "Delay" //d "$delay_in_miliseconds" //f > /dev/null
}

# module functions

is_module_active() {
	cat $base_path/modules/$1/active 2> /dev/null
}

remove_unneeded_stuff_from_module() {
	rm -Rf `find $base_path/modules/$1 -name linux -name darwin`
}
