#!/bin/bash
###################################################################
# PREY Windows Base Functions - by Tomas Pollak (bootlog.org)
# URL: http://preyproject.com
# License: GPLv3
####################################################################

readonly required_net_version='2.0.50727'

get_gateway_ip() {
	gateway_ip=`ipconfig | grep Gateway | sed 's/^.*: //g' | grep -v '^$' | head -1`
}

# returns 1 if it is
is_net_framework_installed() {
	local version=`echo $1 | sed 's/\..\./\./'`
	local results=`reg query "HKLM\Software\Microsoft\NET Framework Setup\NDP'" | sed -e 's/.*NDP\\\v//g' -e 's/\..\./\./'`
	for result in `echo -e $results`; do
		if [[ $result == $version || $result -gt $version ]]; then
			echo 1
		fi
	done
}

try_to_connect() {
	if [ `is_net_framework_installed $required_net_version` == 1 ]; then
		autowc -connect 2> /dev/null
	else
		echo " !! .NET framework version $required_net_version or newer not installed!"
	fi
}

get_current_delay() {
	local delay_in_miliseconds=`reg query "HKLM\Software\Prey" //v "Delay" | grep Delay | sed "s/[^0-9]*//"`
	echo $(($delay_in_miliseconds/60000))
}

update_execution_delay() {
	local delay_in_miliseconds=$(($1*60*1000))
	reg add "HKLM\Software\Prey" //v "Delay" //d "$delay_in_miliseconds" //f > /dev/null
}

# module functions

is_module_active() {
	cat $base_path/modules/$1/active 2> /dev/null
}
