#!/bin/bash
####################################################################
# PREY Location Module Darwin Functions - by Tomas Pollak (bootlog.org)
# URL : http://preyproject.com
# License: GPLv3
####################################################################

function get_wifi_access_points {

	get_wifi_info
	if [ -n "$wifi_info" ]; then

		# $airport -s -x | egrep 'BSSID|CHANNEL<|NOISE|SSID_STR|RSSI' --after-context=1 \
		$airport -s -x | egrep 'BSSID|CHANNEL<|SSID_STR|RSSI' --after-context=1 \
		| egrep -v "AGE|array|WPA" | tr '\n' ' ' \
		| sed -e 's/key//g' -e 's/integer//g' -e 's/string//g' -e 's/[<|>|\/]//g' -e 'y/:/-/' -e 's/ -- /, /g' \
		-e 's/BSSID...\([a-f0-9-]*\)/{"mac_address": "\1"/g' -e 's/-\([0-9]\)-/-0\1-/g' -e 's/"\([0-9]\)-/"0\1-/g' \
		-e 's/CHANNEL...\([0-9]*\)/"channel": \1/g' \
		-e 's/NOISE...\([0-9]*\)/"signal_to_noise": \1/g' \
		-e 's/RSSI...\([0-9]*\)/"signal_strength": \1/g' \
		-e 's/SSID_STR...\([a-zA-Z0-9.-]*\)/"ssid": "\1"}/g'

	fi

}
