#!/bin/bash
####################################################################
# PREY Linux Base Functions - by Tomas Pollak (bootlog.org)
# URL : http://preyproject.com
# License: GPLv3
####################################################################

# we may need to know who the logged user is
readonly logged_user=`who | cut -d' ' -f1 | sort -u | tail -1`
readonly unzip_exlude='-x \*darwin* -x \*bin -x \*.exe'

get_gateway_ip() {
	gateway_ip=`ip r | grep default | cut -d ' ' -f 3`
}

get_wifi_device() {
	if [ ! -n "$wifi_device" ]; then
		wifi_device=`cat /proc/net/wireless | tail -1 | grep -v "nwid" | sed -e 's/^\([^:].*\):.*/\1/' -e 's/\s//g'`
	fi
}

get_wifi_info() {
	if [ ! -n "$wifi_info" ]; then
		wifi_info=`iwconfig 2>&1 | grep -v "no wireless"`
	fi
}

# attempts to connect to the first open public wifi network
# if we dont have NetworkManager available, we use plain iwconfig
try_to_connect() {

	if [ `which nm-applet` ]; then

		# lets restart the NM applet and give it 5 seconds to connect
		killall nm-applet &> /dev/null
		nm-applet --sm-disable & 2> /dev/null
		sleep 5

	else

		get_wifi_device
		if [ -n "$wifi_device" ]; then

			# access_points=`iwlist $wifi_device | awk -F '[ :=]+' '/(ESS|Freq|Qual)/{ printf $3" " } /Encr/{ print $4 }' | sort -k4 -k3nr`
			open_essid=`iwlist $wifi_device scan | awk -F '[ :=]+' '/(ESS|Freq|Qual)/{ printf $3" " } /Encr/{ print $4 }' | sort -k4 -k3nr | grep "off" | head -1 | cut -d ' ' -f1 | sed 's/"//g'`

			# lets see if we have a valid device and essid
			if [ -n $open_essid ]; then
				iwconfig $wifi_device essid $open_essid
			fi

		else

			echo -e ' !! No wifi device found!'

		fi

	fi

}

get_current_delay(){
	crontab -l | grep prey | sed "s/^..\([0-9]*\).*/\1/"
}

update_execution_delay(){
	(crontab -l | grep -v prey; echo "*/$1 * * * * $base_path/prey.sh > /dev/null") | crontab -
}

remove_unneeded_stuff_from_module(){
	rm -Rf `find $base_path/modules/$1 -name darwin -name windows -name *.exe`
}
