#!/bin/bash
###################################################################
# Prey Linux Specific Settings - by Tomas Pollak (bootlog.org)
# URL: http://preyproject.com
# License: GPLv3
####################################################################

readonly logged_user=$(who | cut -d' ' -f1 | tail -1)
readonly system_path="/etc"
readonly users_path="/home"
readonly programs_path="/usr"

if [ -f "/etc/debian-version" ]; then
	network_manager_process="network-manager"
else
	network_manager_process="NetworkManager"
fi

# readonly config_program="$platform_path/prey-config.py"
